### PR TITLE
Fix make file

### PR DESCRIPTION
**Pull request by beaulyddon-wf**
Update of https://github.com/Workiva/furious/pull/135 (Nick is longer at wk)

@nickjoyce-wf @dustinhiatt-wf @rosshendrickson-wf

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 0

**Comment by dustinhiatt-wf** [comment]
+1

**Comment by rosshendrickson-wf** [comment]
+1

**Comment by colefeisthamel-wf** [comment]
RM +1 manually reviewed dependencies.

**Pull request merged**
