### PR TITLE
Update the travis configuration

### PR DESCRIPTION
**Pull request by beaulyddon-wf**
Update the .travis.yml based off an example from google. This should
allow us to stay on latest the latest GAE SDK.

@rosshendrickson-wf @nickjoyce-wf @robertkluin-wf

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 0

**Comment by dustinhiatt-wf** [comment]
+1

**Comment by rosshendrickson-wf** [comment]
+1

**Comment by colefeisthamel-wf** [comment]
RM +1 manually reviewed dependencies

**Pull request merged**
