### PR TITLE
Update the _pkg_meta to 1.6.0

### PR DESCRIPTION
**Pull request by beaulyddon-wf**
Time for a new release

@macleodbroad-wf @rosshendrickson-wf @tylertreat 

FYI @markshaule-wf @brianneal-wf @jasonaguilon-wf

### CODE REVIEW

**Comment by macleodbroad-wf** [comment]
+1

**Comment by tylertreat-wf** [comment]
+1

**Comment by travisreed-wf** [comment]
rosie was turned off on this repo. I turned her back on.

run_merge_script

**Comment by travisreed-wf** [comment]
there wasn't an open release created

run_merge_script

**Pull request merged**
